dir_length = 2  # Uses last 2 directories: "projects/sesh" instead of just "sesh"

sort_order = [
    "config", # show first
    "tmux",
    "zoxide",
]

[[session]]
name = "dev"
path = "."
startup_command = """
~/.config/sesh/default-layout.sh
"""

[[session]]
name = "batapp2"
path = "~/Projects/albertec/new/batapp2"
startup_command = """
~/.config/sesh/default-layout.sh
"""

[[session]]
name = "marula-flow"
path = "~/Projects/albertec/new/marula-flow"
startup_command = """
SESH_GIT_WINDOW=0 ~/.config/sesh/default-layout.sh
"""

[[session]]
name = "marula-smooth"
path = "~/Projects/albertec/new/marula-smooth"
startup_command = """
~/.config/sesh/default-layout.sh
"""

[[session]]
name = "remi"
path = "~/Projects/albertec/new/remi"
startup_command = """
~/.config/sesh/default-layout.sh
"""

[[session]]
name = "pl"
path = "~/Projects/plumbline/avoda-ui"
startup_command = """
~/.config/sesh/pl-layout.sh
"""
